# Generated by Django 5.2.6 on 2025-09-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
